### ISSUE TITLE
Error install package

### ISSUE THREAD

**Issue by rafaelgfirmino** [adrg/go-wkhtmltopdf#1]
Hi, 
when i try to install this package one error ocurred.
```shell
go get github.com/adrg/go-wkhtmltopdf
# github.com/adrg/go-wkhtmltopdf
github.com/adrg/go-wkhtmltopdf/converter.go:7:27: fatal error: wkhtmltox/pdf.h: No such file or directory
compilation terminated.
```

**Comment by adrg** [comment]
@rafaelgfirmino I added a README section with installation instructions for wkhtmltox.

**Comment by LucasVinicius314** [comment]
Just a heads up, if anyone gets this on windows, and then faces "process exited with code 3221225781", it's due to the missing wkhtmltopdf dll, and my case, I just manually copied the dll to golang's bin folder, that houses the go.exe executable and it worked. Restarting my machine could also work because it would update the path with wkhtmltopdf's bin folder, but I haven't tested that yet.
